build: off

install:
  - cinst jdk10 -params 'installdir=C:\\jdk10'
  - SET JAVA_HOME=C:\jdk10
  - SET PATH=C:\jdk10\bin;%PATH%

test_script:
  - gradlew --no-daemon -version
  - gradlew --no-daemon assemble test --tests io.omam.wire.WireEmulatedDeviceTestSuite --stacktrace
