name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build with Gradle'
        run: ./gradlew --warning-mode=all -PenableJaCoCo -Dtags=@EmulatedDevice assemble cucumberTest jacocoCucumberTestReport
      - name: 'Code coverage'
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  windows:
    name: 'Windows'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build with Gradle'
        run: ./gradlew --warning-mode=all -Dtags=@EmulatedDevice assemble cucumberTest

  macos:
    name: 'Mac OS'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build with Gradle'
        run: ./gradlew --warning-mode=all -Dtags=@EmulatedDevice assemble cucumberTest
